### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by delta62**
This pull request adds type metadata so that TypeScript users can use the library.

### CODE REVIEW

**Comment by bjyoungblood** [comment]
Thanks for the contribution! Published as v3.2.0.

**Comment by delta62** [comment]
Happy to help 👍

**Comment by CarsonF** [comment]
@delta62 I'm trying to use this like:
```ts
import ExtendableError from 'es6-error';
```
which tsc/babel compiles but gives runtime error
```
Uncaught TypeError: Super expression must either be null or a function, not undefined
```

This works for me (TS obviously complains):
```ts
import * as ExtendableError from 'es6-error';
```

Thoughts?

**Comment by delta62** [comment]
Yeah, you're right. It looks like the CJS exports are getting set up wrong:

``` js
exports.default = ExtendableError;
module.exports = exports['default']; // Oops, module.exports.default === undefined
```

Since

```js
import ExtendableError from 'es6-error';
```

is sugar for

```js
import { default as ExtendableError } from 'es6-error';
```

TypeScript (I am assuming you're targeting ES5) compiles into something similar to

```js
var ExtendableError = require('es6-error').default;
```

I'd say that the Babel configuration / plugins for CommonJS exports need to be adjusted. I can create a PR in the next few days, but feel free to take it yourself if you need it quicker :)

**Comment by CarsonF** [comment]
@delta62 I think I would be more comfortable with you doing that :)

**Comment by delta62** [comment]
Okay, no problem. I'm out on vacation now, but I'll try to get a PR up when I come back at the end of this week.

**Pull request merged**
