### PR TITLE
remove prepublish script

### PR DESCRIPTION
**Pull request by reggi**
This fires on `npm install`.

### CODE REVIEW

**Comment by reggi** [comment]
Sorry!

**Comment by reggi** [comment]
Did you need to update major version?

**Comment by bjyoungblood** [comment]
[According to the npm docs](https://docs.npmjs.com/misc/scripts), `prepublish` should not run when installing the package as a dependency -- only when running `npm install` inside the package itself.

**Comment by reggi** [comment]
It's never worked right.

https://github.com/npm/npm/issues/3059

**Comment by bjyoungblood** [comment]
I'm not sure if I understand why it's a problem. It's never caused issues for me on this project or on others. If it's breaking something for you, can you describe your use case?

I'd like to avoid removing it if possible, since I'll inevitably forget to recompile before publishing.

**Comment by bjyoungblood** [comment]
Closing this for now. Please reopen if it remains an issue.

**Pull request closed without merging**
