### PR TITLE
Move babel config to .babelrc file

### PR DESCRIPTION
**Pull request by tyscorp**
Fixes issue #19

### CODE REVIEW

**Comment by oreqizer** [comment]
please merge - breaks https://github.com/erikras/redux-form mocking with https://facebook.github.io/jest/ as well as `react-native`

**Comment by oreqizer** [comment]
actually, I just tried this and it doesn't work for me. I still get

`ReferenceError: Unknown plugin "babel-plugin-transform-builtin-extend" specified in "node_modules/es6-error/.babelrc" at 1, attempted to resolve relative to "node_modules/es6-error"`

getting it in `redux-form` when mocking with `jest` (and `babel-jest`), and `react-native`

**Comment by tyscorp** [comment]
Updated to not publish `.babelrc`.

**Comment by oreqizer** [comment]
alright, i'll just close my PR as you fixed it the same way. cheers!

**Comment by tyscorp** [comment]
Oh, I didn't even see that you'd opened a PR. oops

**Comment by oreqizer** [comment]
:smile: np, it was redundant anyway

**Comment by bjyoungblood** [comment]
Thanks! Published v3.0.1 to npm.

**Pull request merged**
