### PR TITLE
Make sure message is propagated

### PR DESCRIPTION
**Pull request by imurchie**
The sub-class does not end up getting a message, so manually save the message.

### CODE REVIEW

**Comment by tchak** [comment]
Much needed pull request!

Just a little sugestion:

``` javascript
if (arguments.length === 0) { message = ''; }
message = message + '';

Object.defineProperty(this, 'message', {
  enumerable : false,
  value : message
});
```

Inspired by https://github.com/0x8890/error-class/blob/master/index.js#L49-L51

**Comment by imurchie** [comment]
The `Object.defineProperty` makes sense. 

I think since this is ES6 it would be better to just use a default argument value rather than deal with `arguments`, though.

**Comment by eliseumds** [comment]
This would be super helpful!

**Comment by tchak** [comment]
@imurchie :+1: old habbits die hard ;)

**Comment by jraede** [comment]
Can you merge this please?

**Comment by andreyvital** [comment]
@bjyoungblood

**Comment by andreyvital** [comment]
@tchak @jraede @imurchie @eliseumds I'm not too much confident that it will be merged soon. Do you know any candidate for this package? I would love to recommend and use it on this plugin I've wrote: [babel-plugin-extends-error](https://github.com/CentaurWarchief/babel-plugin-extends-error).

**Comment by bjyoungblood** [comment]
Sorry it took so long to get this merged. I had notifications for this repo turned off for some reason. Published v2.0.1.

**Comment by tchak** [comment]
\o/

**Comment by andreyvital** [comment]
Unbelievable. Thank you! @bjyoungblood

**Pull request merged**
